# CI for pull requests
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle?learn=continuous_integration&learnProduct=actions
# Using gradle-build-action. See https://github.com/gradle/gradle-build-action

name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        flavour: [
          assembleOculusvrArm64GeckoMetaStore,
          assembleHvrArm64GeckoGeneric,
          assembleHvrArm64GeckoMainlandChina,
          assemblePicoxrArm64GeckoGeneric,
          assembleLynxArm64GeckoGeneric,
          assembleSpacesArm64GeckoGeneric,
          assembleAospX86_64GeckoGeneric
        ]

    steps:
      - name: Checkout Wolvic
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      # Inspired by https://stackoverflow.com/questions/60679609/github-action-to-simply-cat-a-file-to-an-output
      - name: Read wolvic third parties SHA
        run: echo "third_party_sha=$(cat third_party_hash)" >> $GITHUB_ENV

      - name: Checkout third parties
        uses: actions/checkout@v3
        with:
          ref: ${{ env.third_party_sha }}
          repository: Igalia/wolvic-third-parties
          token: ${{ secrets.THIRD_PARTY_PAT }}
          submodules: 'true'
          path: 'third_party'

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5

      - name: Build ${{ matrix.flavour }} Flavour
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ${{ matrix.flavour }}
